function init(self)
	self.ori_pos = go.get_position()
	self.pos = go.get_position()

	timer.delay(0.3, true, function()
		local a = math.random(-500,2600)
		self.pos.x = self.ori_pos.x + a
		local id = factory.create("/ball_factory#bf", self.pos)
	end)
end
function update(self, dt)
end
function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)
end